### ISSUE TITLE
Refactoring required

### ISSUE THREAD

**Issue by purbon** [logstash-plugins/logstash-input-log4j#18]
Hi,
  the code in this plugin needs some :heart: in form or a refactoring that include things like having smaller methods, cleaning up private/public references, performance improvements, etc.

Some comments where introduced in #16

**Comment by jordansissel** [comment]
This plugin is deprecated for security reasons. More details, including a recommended alternative, available here: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-log4j.html#_deprecation_notice
