### ISSUE TITLE
'host' field format is ip_address:port (instead of hostname ?)

### ISSUE THREAD

**Issue by LeRiton** [logstash-plugins/logstash-input-log4j#20]
Hi,

**_Edited, see comment at bottom.**_

Using Logstash 1.5.4 with Log4j input plugin 1.0.0, generated log entries host field is e.g. `"host": "10.XXX.XXX.XXX:62364"` instead of `"host": "myhostname"`.

This isn't consistent with Logstash default, and I believe it should be fixed to hostname, at least through some configuration.

Related:
- [StackOverflow: "log4j tcp appender and logstash source host"](http://stackoverflow.com/questions/28201756/log4j-tcp-appender-and-logstash-source-host)
- [Logstash's (discontinued?) JIRA: "log4j input uses host:port value as host field"](https://logstash.jira.com/browse/LOGSTASH-1914)

Thanks in advance!

**Edit:** nevermind, if Log4j input works as a server socket, there is no easy way to consolidate multiple remote IPs with hostnames.

For local Log4j log analysis, what is your best performance / configuration compromise? Use file input with log file or keep log4j server socket bound to localhost only and use some filter to override host field?

**Comment by jordansissel** [comment]
This plugin is deprecated for security reasons. More details, including a recommended alternative, available here: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-log4j.html#_deprecation_notice
