### ISSUE TITLE
Do not record Location information when they are not available

### ISSUE THREAD

**Issue by wiibaa** [logstash-plugins/logstash-input-log4j#25]
If the socket appender is not activated to write the LocationInformation, the fields file, class, and method will always be:

```
"class" => "?",
"file" => "?:?",
"method" => "?",
```

This correspond to the constant for non-available data as described in https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/spi/LocationInfo.html#NA

The created event should not contains these fields when they are effectively "not available"

**Comment by jordansissel** [comment]
This plugin is deprecated for security reasons. More details, including a recommended alternative, available here: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-log4j.html#_deprecation_notice
