### ISSUE TITLE
Allow to load custom LoggingEvent implementation jar

### ISSUE THREAD

**Issue by wiibaa** [logstash-plugins/logstash-input-log4j#26]
As this plugin is reading Java serialized objects, it is necessary that the serialized object class is loaded in the classpath. If the logging application is using a custom implementation, the necessary library jar must also be loaded by this input.

One example is the Cordys framework as illustrated in https://discuss.elastic.co/t/log4j-socketappender-logstash-tcp-input-ok-log4j-input-ko-solved/36184/21

**Comment by jordansissel** [comment]
Sounds reasonable, though deserializing custom classes could cause security problems.

**Comment by jordansissel** [comment]
This plugin is deprecated for security reasons. More details, including a recommended alternative, available here: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-log4j.html#_deprecation_notice
