### ISSUE TITLE
Research: Accepting both log4j2 and log4j 1.x data

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-log4j#36]
I wrote some sample code to see if log4j2 and log4j 1.2 can coexist, and it works well enough as a client (a logger): https://github.com/jordansissel/experiments/tree/master/java/log4j

When loking at the serialized data sent from the SocketAppender, I find the following for the serialized log class:

* log4j 2: `org.apache.logging.log4j.core.impl.Log4jLogEvent$LogEventProxy`
* log4j 1.2: `org.apache.log4j.spi.LoggingEvent`

**Comment by jordansissel** [comment]
In Logstash 5.0.0, both fail to be received:

* log4j2 - ```[2016-11-28T12:01:44,521][DEBUG][logstash.inputs.log4j    ] Closing connection {:client=>"127.0.0.1:59022", :exception=>#<NoMethodError: undefined method `getRenderedMessage' for #<Java::OrgApacheLoggingLog4jCoreImpl::Log4jLogEvent:0x538e917f>>}```
* log4j 1.2 - ```[2016-11-28T12:00:56,230][DEBUG][logstash.inputs.log4j    ] Closing connection {:client=>"127.0.0.1:48046", :exception=>#<IOError: org.apache.log4j.spi.LoggingEvent; class invalid fo
r deserialization>}```

**Comment by jordansissel** [comment]
> org.apache.log4j.spi.LoggingEvent; class invalid for deserialization

my understanding of this is that this means the the given class does not have `implements Serialiazable` in its class definition.

Log4j 2 has this LoggingEvent without Serializable: https://logging.apache.org/log4j/2.0/log4j-1.2-api/apidocs/org/apache/log4j/spi/LoggingEvent.html

But Log4j 1.2 does have it serializable: https://logging.apache.org/log4j/1.2/apidocs/index.html

My guess here is that log4j2's "1.2 api" is not fully compatible with Log4j 1.2 objects.

**Comment by jordansissel** [comment]
If I build Logstash from master and make the following change, log4j input works for me:

```diff
diff --git a/logstash-core/build.gradle b/logstash-core/build.gradle
index 625b739..0d1c318 100644
--- a/logstash-core/build.gradle
+++ b/logstash-core/build.gradle
@@ -110,7 +110,6 @@ idea {
 }
 
 dependencies {
-    runtime 'org.apache.logging.log4j:log4j-1.2-api:2.6.2'
     compile 'org.apache.logging.log4j:log4j-api:2.6.2'
     compile 'org.apache.logging.log4j:log4j-core:2.6.2'
     compile 'com.fasterxml.jackson.core:jackson-core:2.7.4'
```

The above patch will cause the log4j2 "1.2 api" library to not be included in logstash core. This allows log4j input's included log4j-1.2 jar to provide the LoggingEvent class.

Manual test:

```
% bin/logstash --debug -e 'input { log4j { port => 12346 } }'

{
  "method"      => "?",
  "thread"      => "main",
  "message"     => "OK",
  "priority"    => "WARN",
  "tags"        => [],
  "path"        => "Foo",
  "@timestamp"  => 2016-11-28T23:54:11.887Z,
  "file"        => "?:?",
  "@version"    => "1",
  "host"        => "127.0.0.1:57880",
  "logger_name" => "Foo",
  "class"       => "?",
  "timestamp"   => 1480377251855
}
```

**Comment by clevertension** [comment]
Awesome,this is really a good catch

**Comment by jordansissel** [comment]
PR in logstash: https://github.com/elastic/logstash/pull/6309

**Comment by jordansissel** [comment]
This plugin is deprecated for security reasons. More details, including a recommended alternative, available here: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-log4j.html#_deprecation_notice

**Comment by jordansissel** [comment]
In retrospect, log4j2 can be done when using the JsonLayout

Example:

```
<Configuration status="WARN">
  <Appenders>
    <Socket name="Socket" host="localhost" port="12345">
      <JsonLayout compact="true" eventEol="true" />
    </Socket>
  </Appenders>
  <Loggers>
    <Root level="info">
      <AppenderRef ref="Socket"/>
    </Root>
  </Loggers>
</Configuration>
```

Still, because TCP logging is lossy and could block your application, if either loss or blocking are things you want to avoid, it is strongly recommended that you write to local files and ship the logs with filebeat.
